# Network Configuration - Testnet Setup
# Defines all supported blockchain networks and their tokens

# Base sepolia
[networks.84532]
input_settler_address = "0x2d64BB8efC19d795AAeD9a0675Bfc29fE5F5dA77"
output_settler_address = "0xE177Bb8E48e0d537b3f5e65B92068Aba90523A49"

# RPC endpoints with both HTTP and WebSocket URLs for each network
[[networks.84532.rpc_urls]]
http = "https://sepolia.base.org"
ws = "wss://sepolia.base.org"

[[networks.84532.tokens]]
address = "0x036CbD53842c5426634e7929541eC2318f3dCF7e"
symbol = "USDC"
decimals = 6

# Ethereum Sepolia
[networks.11155111]
input_settler_address = "0x8ba59BB1F81e371F0047456a4765915044c4eED1"
output_settler_address = "0x92C6595624164E17A98790ec659124A53E6bf32E"

# RPC endpoints with both HTTP and WebSocket URLs for each network
[[networks.11155111.rpc_urls]]
http = "https://sepolia.drpc.org"

[[networks.11155111.tokens]]
address = "0xFF34B3d4Aee8ddCd6F9AFFFB6Fe49bD371b8a357"
symbol = "DAI"
decimals = 18

# Optimism sepolia
[networks.11155420]
input_settler_address = "0x2d64BB8efC19d795AAeD9a0675Bfc29fE5F5dA77"
output_settler_address = "0xE177Bb8E48e0d537b3f5e65B92068Aba90523A49"

# RPC endpoints with both HTTP and WebSocket URLs for each network
[[networks.11155420.rpc_urls]]
http = "https://sepolia.optimism.io"

[[networks.11155420.tokens]]
address = "0x5fd84259d66Cd46123540766Be93DFE6D43130D7"
symbol = "USDC"
decimals = 6

# Arbitrum Sepolia
[networks.421614]
input_settler_address = "0xb31d6261a48416A5557807647A6C882e4f654B5b"
output_settler_address = "0x12dd6Ee01c7a04F48d88e70822Cf1AE474467E2D"

# RPC endpoints with both HTTP and WebSocket URLs for each network
[[networks.421614.rpc_urls]]
http = "https://arbitrum-sepolia.drpc.org"

[[networks.421614.tokens]]
address = "0x75faf114eafb1BDbe2F0316DF893fd58CE46AA4d"  # USDC on Arbitrum Sepolia
symbol = "USDC"
decimals = 6
