# OIF Solver Configuration - Testnet USDC Setup

include = [
    "testnet/networks.toml",
    "testnet/api.toml"
]

[solver]
id = "oif-solver-testnet-usdc"
monitoring_timeout_minutes = 5

# ============================================================================
# STORAGE
# ============================================================================
[storage]
primary = "file"
cleanup_interval_seconds = 3600

[storage.implementations.memory]
# Memory storage has no configuration

[storage.implementations.file]
storage_path = "./data/storage"
ttl_orders = 0                  # Permanent
ttl_intents = 86400             # 24 hours
ttl_order_by_tx_hash = 86400    # 24 hours

# ============================================================================
# ACCOUNT
# ============================================================================
[account]
primary = "local"

[account.implementations.local]
private_key = "solver_private_key"

# ============================================================================
# DELIVERY
# ============================================================================
[delivery]
min_confirmations = 3  # Higher confirmations for testnets

[delivery.implementations.evm_alloy]
network_ids = [84532, 11155420, 421614, 11155111]

# ============================================================================
# DISCOVERY
# ============================================================================
[discovery]

[discovery.implementations.onchain_eip7683]
network_ids = [84532, 11155420, 421614, 11155111]

[discovery.implementations.offchain_eip7683]
api_host = "127.0.0.1"
api_port = 8081
network_ids = [84532, 11155420, 421614, 11155111]

# ============================================================================
# ORDER
# ============================================================================
[order]

[order.implementations.eip7683]

[order.strategy]
primary = "simple"

[order.strategy.implementations.simple]
max_gas_price_gwei = 100

# ============================================================================
# SETTLEMENT
# ============================================================================
[settlement]

[settlement.domain]
chain_id = 1
address = "0xB686e4A97821E259d1BB15c5bf13ec96553176d7"

[settlement.implementations.direct]
order = "eip7683"
network_ids = [84532, 11155420, 421614, 11155111]
dispute_period_seconds = 60
# Oracle selection strategy when multiple oracles are available (First, RoundRobin, Random)
oracle_selection_strategy = "First"

# Oracle configuration with multiple oracle support
[settlement.implementations.direct.oracles]
# Input oracles (on origin chains)
input = { 84532 = ["0xDD40C9a79D813e4200795014b8E9e575317596F6"], 11155420 = ["0x6dc56CB6C61f3c5a9148cE1fD1AF7a13B8903980"], 421614 = ["0xedF6cd53008C3EA43e976214F5f6a1A8dBDc6460"], 11155111 = ["0xc04c8A84295F36B53AC109d47C041a258B788268"] }
# Output oracles (on destination chains)
output = { 84532 = ["0xDD40C9a79D813e4200795014b8E9e575317596F6"], 11155420 = ["0x6dc56CB6C61f3c5a9148cE1fD1AF7a13B8903980"], 421614 = ["0xedF6cd53008C3EA43e976214F5f6a1A8dBDc6460"], 11155111 = ["0xc04c8A84295F36B53AC109d47C041a258B788268"] }

# Valid routes: from origin chain -> to destination chains
[settlement.implementations.direct.routes]
84532 = [11155420, 421614, 11155111]     # Base Sepolia can go to all other networks
11155420 = [84532, 421614, 11155111]    # Optimism Sepolia can go to all other networks
421614 = [84532, 11155420, 11155111]    # Arbitrum Sepolia can go to all other networks
11155111 = [84532, 11155420, 421614]    # Ethereum Sepolia can go to all other networks

# ============================================================================
# DEMO SCRIPT CONFIGURATION
# The following sections are used by demo scripts (send_onchain_intent.sh, etc.)
# and are NOT required by the solver itself. The solver only needs the
# configurations above.
# ============================================================================

# Contract addresses for testing (used by demo scripts)
[contracts.origin]
USDC = "0x036CbD53842c5426634e7929541eC2318f3dCF7e"
permit2 = "0x000000000022D473030F116dDEE9F6B43aC78BA3"

[contracts.destination]
USDC = " 0x5fd84259d66Cd46123540766Be93DFE6D43130D7"
permit2 = "0x000000000022D473030F116dDEE9F6B43aC78BA3"

# Test accounts (used by demo scripts)
[accounts]
solver = "0xbe2D5EBF89baD8f8c92ED2382c16ECB90DD37be2"
user = "0xf1828Ea4C9480F87620E538c80b6134A2e611ea9"
user_private_key = "user_private_key"
recipient = "0x40C93020a2964dc79456443B938D0cA556117317"
