[package]
name = "solver-validators"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
solver-types = { path = "../solver-types" }
async-trait = { workspace = true }
tokio = { workspace = true }